const boardDummy = [
    {
        "id": 10,
        "title": "title9",
        "content": "content9",
        "hits": 0,
        "views": 0,
        "dislikes": 0,
        "reported": 0,
        "hidden": "0",
        "createdAt": "2023-06-07T16:54:04.000Z",
        "updatedAt": null,
        "userId": 2,
        "categoryId": 1,
        "userNickname": "nick2",
        "userImg": null,
        "userGrade": "grade2",
        "categoryName": "category1"
    },
    {
        "id": 6,
        "title": "updated",
        "content": "update!😁",
        "hits": 0,
        "views": 1,
        "dislikes": 0,
        "reported": 0,
        "hidden": "0",
        "createdAt": "2023-06-05T04:08:47.000Z",
        "updatedAt": "2023-06-05T06:32:52.000Z",
        "userId": 1,
        "categoryId": 1,
        "userNickname": "nick1",
        "userImg": null,
        "userGrade": "grade1",
        "categoryName": "category1"
    },
    {
        "id": 5,
        "title": "Title2",
        "content": "2",
        "hits": 0,
        "views": 1,
        "dislikes": 0,
        "reported": 0,
        "hidden": "0",
        "createdAt": "2023-06-05T04:08:44.000Z",
        "updatedAt": "2023-06-05T04:08:44.000Z",
        "userId": 3,
        "categoryId": 1,
        "userNickname": "test3",
        "userImg": "https://t1.daumcdn.net/cfile/tistory/99B5B5405CE09E4222",
        "userGrade": "admin",
        "categoryName": "category1"
    },
    {
        "id": 1,
        "title": "title1",
        "content": "content1",
        "hits": 0,
        "views": 0,
        "dislikes": 0,
        "reported": 0,
        "hidden": "0",
        "createdAt": null,
        "updatedAt": null,
        "userId": 1,
        "categoryId": 1,
        "userNickname": "nick1",
        "userImg": null,
        "userGrade": "grade1",
        "categoryName": "category1"
    }
]